//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveLetter.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _string {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _string() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveLetter.Properties.string", typeof(_string).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a baron.
        /// </summary>
        internal static string ABaron {
            get {
                return ResourceManager.GetString("ABaron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a countess.
        /// </summary>
        internal static string ACountess {
            get {
                return ResourceManager.GetString("ACountess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate tutorial.
        /// </summary>
        internal static string ActivateTutorial {
            get {
                return ResourceManager.GetString("ActivateTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a guard.
        /// </summary>
        internal static string AGuard {
            get {
                return ResourceManager.GetString("AGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a handmaid.
        /// </summary>
        internal static string AHandmaid {
            get {
                return ResourceManager.GetString("AHandmaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a king.
        /// </summary>
        internal static string AKing {
            get {
                return ResourceManager.GetString("AKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a priest.
        /// </summary>
        internal static string APriest {
            get {
                return ResourceManager.GetString("APriest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a prince.
        /// </summary>
        internal static string APrince {
            get {
                return ResourceManager.GetString("APrince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a princess.
        /// </summary>
        internal static string APrincess {
            get {
                return ResourceManager.GetString("APrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baron.
        /// </summary>
        internal static string Baron {
            get {
                return ResourceManager.GetString("Baron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baron Value 3 : {0}  Compare your hand with another player, {1} the one with the card with the lowest value is eleminated.
        /// </summary>
        internal static string BaronEffectValue {
            get {
                return ResourceManager.GetString("BaronEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a type of card !.
        /// </summary>
        internal static string ChooseATypeOfCard {
            get {
                return ResourceManager.GetString("ChooseATypeOfCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparing hand of {0} and {1}.
        /// </summary>
        internal static string ComparingHandsOfAnd {
            get {
                return ResourceManager.GetString("ComparingHandsOfAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Countess.
        /// </summary>
        internal static string Countess {
            get {
                return ResourceManager.GetString("Countess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Countess Value : 7 {0} : If you have this card in your hand at the same time as king or Prince ,{1} you must discard this card .
        /// </summary>
        internal static string CountessEffectValue {
            get {
                return ResourceManager.GetString("CountessEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desactivate tutorial.
        /// </summary>
        internal static string DesactivateTutorial {
            get {
                return ResourceManager.GetString("DesactivateTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} discarded the Princess ! .
        /// </summary>
        internal static string DiscardedPrincess {
            get {
                return ResourceManager.GetString("DiscardedPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} does not have the card {1}.
        /// </summary>
        internal static string DoesNotHaveTheCard {
            get {
                return ResourceManager.GetString("DoesNotHaveTheCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Draw !.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effect volume.
        /// </summary>
        internal static string effectVolume {
            get {
                return ResourceManager.GetString("effectVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The game will begin.
        /// </summary>
        internal static string GameWillBegin {
            get {
                return ResourceManager.GetString("GameWillBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard.
        /// </summary>
        internal static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard Value : 1 {0} Choose a player and try to guess which card he has in his hand (except the guard), {1} if you are right the player is eleminated..
        /// </summary>
        internal static string GuardEffectValue {
            get {
                return ResourceManager.GetString("GuardEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} had to discard his hand !.
        /// </summary>
        internal static string HadToDiscard {
            get {
                return ResourceManager.GetString("HadToDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Handmaid.
        /// </summary>
        internal static string Handmaid {
            get {
                return ResourceManager.GetString("Handmaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Handmaid Value 4 {0} : You are protected until the next turn.
        /// </summary>
        internal static string HandmaidEffectValue {
            get {
                return ResourceManager.GetString("HandmaidEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has reached the limit number of marker, he won !.
        /// </summary>
        internal static string HasReachedLimitNumberMarker {
            get {
                return ResourceManager.GetString("HasReachedLimitNumberMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} won the round with the most strongest card discarded.
        /// </summary>
        internal static string hasTheMostStrongestCardDiscarded {
            get {
                return ResourceManager.GetString("hasTheMostStrongestCardDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} won the round with the strongest card.
        /// </summary>
        internal static string hasTheStrongestCard {
            get {
                return ResourceManager.GetString("hasTheStrongestCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has won ! .
        /// </summary>
        internal static string HasWon {
            get {
                return ResourceManager.GetString("HasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here&apos;s the hand of {0}.
        /// </summary>
        internal static string HeresTheHandOfYourTarget {
            get {
                return ResourceManager.GetString("HeresTheHandOfYourTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is out of the game !.
        /// </summary>
        internal static string IsOutOfTheGame {
            get {
                return ResourceManager.GetString("IsOutOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is protected for one turn.
        /// </summary>
        internal static string IsProtectedForOneTurn {
            get {
                return ResourceManager.GetString("IsProtectedForOneTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is the last player, he won the round !.
        /// </summary>
        internal static string IsTheLastPlayer {
            get {
                return ResourceManager.GetString("IsTheLastPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Its Not Your Turn.
        /// </summary>
        internal static string ItsNotYourTurn {
            get {
                return ResourceManager.GetString("ItsNotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à King Value : 6 {0}  Switch your hand with another player.
        /// </summary>
        internal static string KingEffectValue {
            get {
                return ResourceManager.GetString("KingEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master volume.
        /// </summary>
        internal static string masterVolume {
            get {
                return ResourceManager.GetString("masterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music volume.
        /// </summary>
        internal static string musicVolume {
            get {
                return ResourceManager.GetString("musicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Must Play Countess !.
        /// </summary>
        internal static string MustPlayCountess {
            get {
                return ResourceManager.GetString("MustPlayCountess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mute.
        /// </summary>
        internal static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Round {0}.
        /// </summary>
        internal static string NewRound {
            get {
                return ResourceManager.GetString("NewRound", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Recherche une chaîne localisée semblable à Not enough player.
        /// </summary>
        internal static string NotEnoughPlayer
        {
            get
            {
                return ResourceManager.GetString("NotEnoughPlayer", resourceCulture);
            }
        }

        ///   Recherche une chaîne localisée semblable à Play one card.
        /// </summary>
        internal static string Play1Card {
            get {
                return ResourceManager.GetString("Play1Card", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player {0} play.
        /// </summary>
        internal static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priest.
        /// </summary>
        internal static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priest Value 2 : {0} Look the hand of another player.
        /// </summary>
        internal static string PriestEffectValue {
            get {
                return ResourceManager.GetString("PriestEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prince.
        /// </summary>
        internal static string Prince {
            get {
                return ResourceManager.GetString("Prince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prince Value : 5 {0}  Choose a player (including you), {1} the player discard his hand to pick another card.
        /// </summary>
        internal static string PrinceEffectValue {
            get {
                return ResourceManager.GetString("PrinceEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Princess.
        /// </summary>
        internal static string Princess {
            get {
                return ResourceManager.GetString("Princess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Princess Value : 8 {0} : If you discard this card you are eleminated from the round.
        /// </summary>
        internal static string PrincessEffectValue {
            get {
                return ResourceManager.GetString("PrincessEffectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score : {0}.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select 1 player.
        /// </summary>
        internal static string Select1Player {
            get {
                return ResourceManager.GetString("Select1Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show message box.
        /// </summary>
        internal static string showMessageBox {
            get {
                return ResourceManager.GetString("showMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show full screen message.
        /// </summary>
        internal static string showMessageFullscreen {
            get {
                return ResourceManager.GetString("showMessageFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Someone leave !.
        /// </summary>
        internal static string SomeoneLeave {
            get {
                return ResourceManager.GetString("SomeoneLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting new game.
        /// </summary>
        internal static string StartingNewGame {
            get {
                return ResourceManager.GetString("StartingNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} switched his hand with {1}.
        /// </summary>
        internal static string SwitchHands {
            get {
                return ResourceManager.GetString("SwitchHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Take 1 card from deck.
        /// </summary>
        internal static string Take1CardFromTheDeck {
            get {
                return ResourceManager.GetString("Take1CardFromTheDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The game deck is empty.
        /// </summary>
        internal static string TheGameDeckIsEmpty {
            get {
                return ResourceManager.GetString("TheGameDeckIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no avalaible target.
        /// </summary>
        internal static string ThereAreNoAvalaibleTarget {
            get {
                return ResourceManager.GetString("ThereAreNoAvalaibleTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} thinks that {1} has {2}.
        /// </summary>
        internal static string ThinksThatHas {
            get {
                return ResourceManager.GetString("ThinksThatHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} uses a priest to see the hand of {1}.
        /// </summary>
        internal static string UseAPriestToSee {
            get {
                return ResourceManager.GetString("UseAPriestToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Well guessed.
        /// </summary>
        internal static string WellGuessed {
            get {
                return ResourceManager.GetString("WellGuessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} won the battle against {1} !.
        /// </summary>
        internal static string WonTheBattle {
            get {
                return ResourceManager.GetString("WonTheBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot pick more than one card !.
        /// </summary>
        internal static string YouCannotPickMoreThanOneCard {
            get {
                return ResourceManager.GetString("YouCannotPickMoreThanOneCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to pick a card first !.
        /// </summary>
        internal static string YouNeedToPickACardFirst {
            get {
                return ResourceManager.GetString("YouNeedToPickACardFirst", resourceCulture);
            }
        }
    }
}
